eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8081/eureka/

server:
  port: 8086

spring:
  sleuth:
    sampler:
      probability: 1
  zipkin:
      base-url: http://localhost:9411/

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 60000
zuul:
  prefix: /api
  routes:
    libraryService:
      path: /services/**
      service-id: library-service



